# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY {
  globalAuthRule: AuthRule = { allow: public }
} # FOR TESTING ONLY!
type CharitiesWithCategories @model {
  id: ID
  name: String!
  mission: String
  email: String
  phone: String
  website: String
  program: String
  programDescription: String
  processLink: String
  product: String
  category: String
}

type User @model {
  id: ID!
  email: String!
  militaryBranch: String
  age: String
  phoneNumber: String
  profilePicture: String
  address: Address
}

type Address {
  street: String
  city: String
  state: String
  zipCode: String
  country: String
}

type Bookmark @model {
  id: ID!
  userId: ID!
  charityName: String!
  charityId: String
  category: String
  createdAt: AWSDateTime
}
